# tools/generate_init.py

import os
import ast


def extract_classes_from_file(file_path: str) -> list:
    """Extract all class names defined in a Python file using AST."""

    with open(file_path, "r", encoding="utf-8") as f:
        node = ast.parse(f.read(), filename=file_path)

    classes = [
        n.name for n in node.body

        if isinstance(n, ast.ClassDef)
    ]

    return classes


def generate_init(files_path):
    print(files_path)

    files = os.listdir(files_path)

    imports = []
    exported_classes = []

    # Get all Python files, except __init__.py
    for filename in files:
        if not filename.endswith(".py"):
            continue

        if filename == "__init__.py":
            continue

        module_name = filename.replace(".py", "")
        file_path = os.path.join(files_path, filename)

        classes = extract_classes_from_file(file_path)

        if not classes:
            continue  # skip files without classes

        for cls in classes:
            imports.append(f"from .{module_name} import {cls}")
            exported_classes.append(cls)

    # Sort alphabetically for organization
    imports.sort()
    exported_classes.sort()

    # Build final content
    lines = [
        "# Auto-generated by tools/generate_init.py\n",
        "# Do not edit manually.\n",
    ]

    lines.extend(imports)

    # Add __all__ block
    lines.append("\n__all__ = [")

    for cls in exported_classes:
        lines.append(f"    \"{cls}\",")

    lines.append("]\n")

    final_text = "\n".join(lines)

    # Write __init__.py
    init_path = os.path.join(files_path, "__init__.py")

    with open(init_path, "w", encoding="utf-8") as f:
        f.write(final_text)

        print("✔ __init__.py generated successfully!")
        print("----------------------------------")
        print("Content:")
        print(final_text)

if __name__ == "__main__":
    generate_init(files_path=input("Enter the path: "))

